import { Country } from "../country-model/country.model";

export class UserAffiliate {
  id: number;
  user_name: string;
  name: string;
  password: string;
  is_affiliate: number;
  last_name: string;
  phone: string;
  identification: string;
  email: string;
  zip_code: string;
  country: number;
  state_place: string;
  city: string;
  address: string;
  birthday: Date;
  tax_id: string;
  binary_side_name: string;
  beneficiary_name: string;
  father_user: UserAffiliate;
  father_user_level: UserAffiliate;
  status: number;
  affiliate_type: string;
  affiliate_mode: string;
  external_grading_id: number;
  external_grading_before_id: number;
  activation_date: Date;
  verificated_email: boolean;
  card_id_authorization: boolean;
  father: number;
  sponsor: number;
  binary_sponsor: number;
  binary_matrix_side: number;
  side: number;
  created_at: Date;
  country_information: Country;
  legal_authorized_first: string;
  legal_authorized_second: string;
  external_product_id: number;
  image_id_path: string;
  image_profile_url: string;
  updated_at?: Date;
  termsConditions: boolean;
  message_alert?: number;

  constructor() {
    this.id = 0;
    this.user_name = '';
    this.is_affiliate = 1;
    this.name = '';
    this.password = '';
    this.last_name = '';
    this.phone = '';
    this.email = '';
    this.identification = '';
    this.binary_side_name = '';
    this.zip_code = '';
    this.country = 0;
    this.external_grading_id = 0;
    this.side = 0;
    this.state_place = '';
    this.city = '';
    this.birthday = new Date();
    this.tax_id = '';
    this.beneficiary_name = '';
    this.status = 0;
    this.affiliate_type = '';
    this.affiliate_mode = '';
    this.activation_date = new Date();
    this.verificated_email = false;
    this.father = 0;
    this.sponsor = 0;
    this.binary_sponsor = 0;
    this.binary_matrix_side = 0;
    this.created_at = new Date();
    this.external_product_id = 0;
    this.image_id_path = '';
    this.termsConditions = false;
  }
}
