import { RouteInfo } from './sidebar.metadata';
export const ROUTES: RouteInfo[] = [
  {
    path: '/app/home',
    title: 'MENUITEMS.HOME.TEXT',
    iconType: 'feather',
    icon: 'home',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  // {
  //   path: '',
  //   title: 'MENUITEMS.BILLING-PURCHASE.TEXT',
  //   iconType: 'feather',
  //   icon: 'globe',
  //   class: 'menu-toggle',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   submenu: [
  //     {
  //       path: '/app/savings-plans',
  //       title: 'SAVINGS-PLANS-PAGE.TITLE.TEXT',
  //       iconType: 'feather',
  //       icon: 'book-open',
  //       class: '',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       submenu: [],
  //     },
  //     // {
  //     //   path: '/app/savings-plans-one-b',
  //     //   title: 'SAVINGS-PLANS-ONEB-PAGE.TITLE.TEXT',
  //     //   iconType: 'feather',
  //     //   icon: 'book-open',
  //     //   class: '',
  //     //   groupTitle: false,
  //     //   badge: '',
  //     //   badgeClass: '',
  //     //   submenu: [],
  //     // },
  //     {
  //       path: '/app/billing-purchase',
  //       title: 'BILLING-PURCHASE-PAGE.SUBTITLE.TEXT',
  //       iconType: 'feather',
  //       icon: 'book-open',
  //       class: '',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       submenu: [],
  //     }
  //   ],
  // },
  {
    path: '',
    title: 'Ecommerce',
    iconType: 'feather',
    icon: 'shopping-cart',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [
      // {
      //   path: '/app/educational-courses',
      //   title: 'MENUITEMS.EDUCATIONAL-COURSES.TEXT',
      //   iconType: 'feather',
      //   icon: 'book-open',
      //   class: '',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   submenu: [],
      // },
      {
        path: '/app/recycoin',
        title: 'RecyCoin',
        iconType: 'feather',
        icon: 'book-open',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      // {
      //   path: '/app/funding-account',
      //   title: 'MENUITEMS.FUNDING-ACCOUNTS.TEXT',
      //   iconType: 'feather',
      //   icon: 'dollar-sign',
      //   class: '',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   submenu: [],
      // },
      // {
      //   path: '/app/services-and-products',
      //   title: 'MENUITEMS.SERVICES-AND-PRODUCTS.TEXT',
      //   iconType: 'feather',
      //   icon: 'briefcase',
      //   class: '',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   submenu: [],
      // }
    ],
  },
  {
    path: '/app/billing-purchases',
    title: 'MENUITEMS.BILLING-MY-PURCHASES.TEXT',
    iconType: 'feather',
    icon: 'list',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: '/app/network',
    title: 'MENUITEMS.NETWORK.TEXT',
    iconType: 'feather',
    icon: 'rss',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: '/app/requests',
    title: 'MENUITEMS.REQUEST-PAY.TEXT',
    iconType: 'feather',
    icon: 'shopping-bag',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: '/app/wallet',
    title: 'MENUITEMS.WALLET.TEXT',
    iconType: 'feather',
    icon: 'credit-card',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [

      // {
      //   path: '/app/request-wallet',
      //   title: 'MENUITEMS.REQUEST-WALLET.TEXT',
      //   iconType: '',
      //   icon: '',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   submenu: [],
      // },
      // {
      //   path: '/app/commissions',
      //   title: 'MENUITEMS.MY-COMMISSIONS.TEXT',
      //   iconType: '',
      //   icon: '',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   submenu: [],
      // },
      // {
      //   path: '/app/commissions-balance',
      //   title: 'MENUITEMS.COMMISSIONS-BALANCE.TEXT',
      //   iconType: '',
      //   icon: '',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   submenu: [],
      // },
    ],
  },

  // {
  //   path: '/app/addresses',
  //   title: 'MENUITEMS.ADDRESSES.TEXT',
  //   iconType: 'feather',
  //   icon: 'map-pin',
  //   class: '',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   submenu: [],
  // },
  {
    path: '/app/tickets',
    title: 'MENUITEMS.TOOLS.TEXT',
    iconType: 'feather',
    icon: 'tag',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [
      {
        path: '/app/tickets',
        title: 'MENUITEMS.MY-TICKETS.TEXT',
        iconType: 'feather',
        icon: 'book-open',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      }
    ]
  },
  //     {
  //       path: '/app/news',
  //       title: 'MENUITEMS.NEWS.TEXT',
  //       iconType: 'feather',
  //       icon: 'book-open',
  //       class: '',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       submenu: [],
  //     },
  //   ],

  // },


];
